### ISSUE TITLE
报错：文件缺失

### ISSUE THREAD

**Issue by Lucency0331** [LHRLAB/ChatKBQA#1]

**Comment by Lucency0331** [comment]
作者您好，在复现您的项目时，在管理Virtuoso服务这步，运行”python3 virtuoso.py start 3001 -d virtuoso_db“但是出现如下错误
RUNNING: /xiangmu/ChatKBQA/Freebase-Setup/virtuoso_db/bin/virtuoso-t +configfile virtuoso_db/virtuoso.ini +wait
/bin/sh: 1: /xiangmu/ChatKBQA/Freebase-Setup/virtuoso_db/bin/virtuoso-t: not found
但是从网站下载的virtuoso_db.zip中并没有这些需要的文件，我是需要进行一些其他操作来生成这些文件吗

**Comment by LHRLAB** [comment]
这个是从dropout下载的还是从百度网盘？

**Comment by Lucency0331** [comment]
没事了，已经解决这个问题了，我是一个研一学生，第一次用virtuoso，以为这是个必需的文件，结果是一个我需要提前准备好的软件环境，感谢您这么晚还回复我的问题。

**Comment by LHRLAB** [comment]
OK

**Comment by slintday** [comment]
作者您好，我们遇到了错误：
运行python3 virtuoso.py start 3001 -d virtuoso_db 没有错误RUNNING: /ChatKBQA/Freebase-Setup/virtuoso-opensource/bin/virtuoso-t +configfile virtuoso_db/virtuoso.ini +wait

但是打开打开 http://localhost:3001时
Error HTTP/1.1 404 File not found
The requested URL was not found    URI  = '/'

**Comment by LHRLAB** [comment]
应该在http://localhost:3001/sparql

**Comment by slintday** [comment]
感谢感谢

**Comment by Lucency0331** [comment]
作者您好，在“Prepare data for training and evaluation”这步操作中，运行如下代码
“python data_process.py --action merge_all --dataset WebQSP --split test”
出现了如下错误
pyodbc.Error: ('S2801', '[S2801] [OpenLink][Virtuoso iODBC Driver]CL033: Connect failed to localhost:13001 = localhost:13001. (-1) (SQLDriverConnect)')
但是我已经打开了virtuoso服务，您在创作过程中出现过这个错误吗

**Comment by Lucency0331** [comment]
作者您好，我在训练chatglm2时，已经将参数中的batchsize调到了1，但还是会报显存不足，我是否还能有其他可以调整的参数来减少显存消耗，我使用的是nvidia rtx3090  24g  *2

**Comment by LHRLAB** [comment]
我们所有实验实在A40（48G）上做的，如果glm的实验batchsize调到了1还不行，那只能试着用多卡训练了，可以参考https://github.com/hiyouga/LLaMA-Factory，或者换成llama-2-7b模型。

**Comment by LHRLAB** [comment]
我们所有实验实在A40（48G）上做的，如果glm的实验batchsize调到了1还不行，那只能试着用多卡训练了，可以参考https://github.com/hiyouga/LLaMA-Factory，或者换成llama-2-7b模型。

**Comment by LHRLAB** [comment]
我们所有实验实在A40（48G）上做的，如果glm的实验batchsize调到了1还不行，那只能试着用多卡训练了，可以参考[LLaMA-Factory](https://github.com/hiyouga/LLaMA-Factory)，或者换成llama-2-7b模型。

**Comment by Lucency0331** [comment]
非常感谢，不知道我能否有幸添加您的微信，向您请教后续问题

**Comment by LHRLAB** [comment]
好的，lhr1846205978

**Comment by wwwww122** [comment]
> 非常感谢，不知道我能否有幸添加您的微信，向您请教后续问题
您好 请问可以加一下您的联系方式吗？有一些问题想交流一下 @Lucency0331

**Comment by LHRLAB** [comment]
好的

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Lucency0331 ***@***.***&gt;;
发送时间：2023年11月21日(星期二) 下午3:11
收件人："LHRLAB/ChatKBQA" ***@***.***&gt;;
抄送："Haoran Luo ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [LHRLAB/ChatKBQA] 报错：文件缺失 (Issue #1)
-----------------------------------

 

  
非常感谢，不知道我能否有幸添加您的微信，向您请教后续问题
 您好 请问可以加一下您的联系方式吗？有一些问题想交流一下 @Lucency0331

**Comment by Lucency0331** [comment]
> > 非常感谢，不知道我能否有幸添加您的微信，向您请教后续问题
> > 您好 请问可以加一下您的联系方式吗？有一些问题想交流一下 @Lucency0331

15690466956

**Comment by GP-12138** [comment]
作者您好，冒昧打扰！
我在准备好微调数据和模型后进行步骤Train and test LLM model for Logical Form Generation。执行模型训练时任务被接收，但很快就退出了，并未执行训练，请问是有什么关键步骤我没有执行吗？

**Comment by xiaoma444** [comment]
> 没事了，已经解决这个问题了，我是一个研一学生，第一次用virtuoso，以为这是个必需的文件，结果是一个我需要提前准备好的软件环境，感谢您这么晚还回复我的问题。

您可以告诉我需要准备好什么软件环境吗，我也遇到了相同的问题？感谢。
