### ISSUE TITLE
Uploading Processed Files

### ISSUE THREAD

**Issue by YaooXu** [LHRLAB/ChatKBQA#11]
Thanks for sharing the codes! Could you please upload processed files for training and evaluation (e.g., WebQSP/generation/* and CWQ/generation/*), because I found that label map is empty using my Freebase deployed before. Thanks a lot!

**Comment by LHRLAB** [comment]
Updated.
<img width="949" alt="image" src="https://github.com/LHRLAB/ChatKBQA/assets/93914328/530155e1-29e1-4f93-ad83-e63fe6db441f">

**Comment by YaooXu** [comment]
Thanks for your quick reply!
