### ISSUE TITLE
oracle entity linking annotations

### ISSUE THREAD

**Issue by quqxui** [LHRLAB/ChatKBQA#15]
Hi, 

Thanks for the outstanding work your team has accomplished. 

I have a question: Could you kindly explain what "Oracle Entity Linking Annotations" refer to in your work? 

Thank you in advance for your time and assistance.

**Comment by LHRLAB** [comment]
Setup that utilizes topic entity annotation information.

**Comment by quqxui** [comment]
In Table 1, the result of **ChatKBQA (ours)** use entity similarity and relation similarity, while the result of **ChatKBQA* (ours)** use oracle entity linking annotations and relation similarity. Do I understand correctly?

**Comment by LHRLAB** [comment]
Yes.

**Comment by 6-git** [comment]
Excuse me, based on the code below, I'd like to know if 'Oracle Entity Linking Annotations' refers to the process of extracting entities from the SPARQL provided by the dataset to replace the method of using entity similarity for entity search.

`
def extract_mentioned_entities_from_sparql(sparql:str) -> List[str]:
    """extract entity from sparql"""
    sparql = sparql.replace('(',' ( ').replace(')',' ) ')
    toks = sparql.split(' ')
    toks = [x.replace('\t.','') for x in toks if len(x)]
    entity_tokens = []
    for t in toks:
        if t.startswith('ns:m.') or t.startswith('ns:g.'):
            entity_tokens.append(t[3:])
        
    entity_tokens = list(set(entity_tokens))
    return entity_tokens
`
