### ISSUE TITLE
How to transform s-expr / sparql_query to path?

### ISSUE THREAD

**Issue by quqxui** [LHRLAB/ChatKBQA#17]
Hi, thank for your great job.

Do you know how to transform a s-expr / sparql_query  to a path from source entity to target entity? Rather than only get the final answer with `execute_query_with_odbc(sparql_query)`

 I'm not familirary about the SPARQL system and the usages of pyodbc.

 Any assistance you could provide would be greatly appreciated.

**Comment by LHRLAB** [comment]
You can output all intermediate variables in the SELECT part of SPARQL.

**Comment by quqxui** [comment]
Thank you!
