### ISSUE TITLE
TypeError: sdp_kernel() got an unexpected keyword argument 'enable_mem_efficient'

### ISSUE THREAD

**Issue by ganlinganlin** [LHRLAB/ChatKBQA#3]
I encountered this error during the training of Baichuan2-7b, and after searching for relevant solutions, I found that upgrading torch to version 2.0 was suggested. However, I am curious if there are any alternative solutions without upgrading torch.

TypeError: sdp_kernel() got an unexpected keyword argument 'enable_mem_efficient'

**Comment by LHRLAB** [comment]
We are using PyTorch version 1.13.1. Other related dependencies have been listed in the requirements.txt file.
