### ISSUE TITLE
 Checkpoint seems not contain LoRA weights 

### ISSUE THREAD

**Issue by FUTUREEEEEE** [LHRLAB/ChatKBQA#4]
Hi,
Thanks for sharing the code, I was trying to run it, and get stack in 
`python -u LLMs/LLaMA/src/beam_output_eva.py --model_name_or_path meta-llama/Llama-2-7b-hf --dataset_dir LLMs/data --dataset WebQSP_Freebase_NQ_test --template llama2 --finetuning_type lora --checkpoint_dir Reading/LLaMA2-7b/WebQSP_Freebase_NQ_lora_epoch100/checkpoint --num_beams 15`

I have finish the 100 epoch training on WebQSP and get following error:
`AssertionError: Provided path (Reading/LLaMA2-7b/WebQSP_Freebase_NQ_lora_epoch100/checkpoint) does not contain a LoRA weight.`

here is the screen shot for the checkpoint I got after training:
![image](https://github.com/LHRLAB/ChatKBQA/assets/52389798/65ba5769-f78b-474d-9b46-75da4ca9a763)

Looking forward to your response.

Best regards,
Xiaqiang

**Comment by LHRLAB** [comment]
This seems strange; perhaps you need to debug and check if the code for saving model parameters was successfully executed during the training process.

**Comment by FUTUREEEEEE** [comment]
> This seems strange; perhaps you need to debug and check if the code for saving model parameters was successfully executed during the training process.

Hi, 
I have done some debug, and find that adapter_model.safetensors seems contains the lora weight, and I change `WEIGHTS_NAME` to   `SAFETENSORS_WEIGHTS_NAME` fix this issue.

https://github.com/LHRLAB/ChatKBQA/blob/a63ff0fefe02161b2367e49992098803f8dbd425/LLMs/LLaMA/src/llmtuner/tuner/core/adapter.py#L66

![image](https://github.com/LHRLAB/ChatKBQA/assets/52389798/3a2d2784-95a2-4e33-955c-d64318eb50e0)


Do you this I load the lora weight correctly? I will update the result when I finish eval.

**Comment by FUTUREEEEEE** [comment]
The eval results are as following, is this match the original results?


`Total lines: 1639
Matched lines: 1225
Will Matched lines: 1500
Percentage of matched lines: 74.74%
Percentage of will matched lines: 91.52%`
