### ISSUE TITLE
疑似文件缺失

### ISSUE THREAD

**Issue by 52566rz** [LHRLAB/ChatKBQA#9]
作者您好，我是一名研0小白，想要学习您的代码。在查看train_bash.py时from llmtuner import run_exp提示报错，发现在Github上提供的代码llmtuner包中没有run_exp，在beam_output_eva.py也有类似情况。希望作者大大能够帮我解答疑惑，问题如有冒犯请多多谅解。祝作者大大天天开心，paper多多。

**Comment by LHRLAB** [comment]
<img width="1378" alt="image" src="https://github.com/LHRLAB/ChatKBQA/assets/93914328/34a2b56f-3bb8-4430-9ae7-cc2677951969">

**Comment by 52566rz** [comment]
非常感谢
